# Generated by Django 2.0.9 on 2018-12-14 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pab_data',
            new_name='pub_date',
        ),
    ]
